FROM kathrinklee/samtools:latest
WORKDIR /app
RUN apt-get update && \
    apt-get install -y \
	build-essential \
    cmake \
	make \
    git-core \
    zlib1g-dev \
    libncurses-dev \
	patch
RUN git clone https://github.com/genome/bam-readcount.git
WORKDIR /app/bam-readcount/
RUN cmake .
RUN make
RUN cp /app/bam-readcount/bin/bam-readcount /usr/bin
